// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5cH2oTCKraNz15n2Kwe-_BBkNG70m22o',
    appId: '1:979967478226:web:b482571805147f8693600b',
    messagingSenderId: '979967478226',
    projectId: 'moviedb-ceceb',
    authDomain: 'moviedb-ceceb.firebaseapp.com',
    databaseURL: 'https://moviedb-ceceb-default-rtdb.firebaseio.com',
    storageBucket: 'moviedb-ceceb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehX9VO52U5W9q0vxjOZr8SnTHumV7cC8',
    appId: '1:979967478226:android:1b25b0cfb6ea224e93600b',
    messagingSenderId: '979967478226',
    projectId: 'moviedb-ceceb',
    databaseURL: 'https://moviedb-ceceb-default-rtdb.firebaseio.com',
    storageBucket: 'moviedb-ceceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdGrcQtejm14gURwu4YfsYAvCGzo2Cf10',
    appId: '1:979967478226:ios:98cf255752390f6893600b',
    messagingSenderId: '979967478226',
    projectId: 'moviedb-ceceb',
    databaseURL: 'https://moviedb-ceceb-default-rtdb.firebaseio.com',
    storageBucket: 'moviedb-ceceb.appspot.com',
    iosClientId: '979967478226-4bfdgjs6ee23vgm3j8o2l8blt296vfr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdGrcQtejm14gURwu4YfsYAvCGzo2Cf10',
    appId: '1:979967478226:ios:98cf255752390f6893600b',
    messagingSenderId: '979967478226',
    projectId: 'moviedb-ceceb',
    databaseURL: 'https://moviedb-ceceb-default-rtdb.firebaseio.com',
    storageBucket: 'moviedb-ceceb.appspot.com',
    iosClientId: '979967478226-4bfdgjs6ee23vgm3j8o2l8blt296vfr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieDb',
  );
}
